build: off

version: "1.0.0-{build}"

branches:
  only:
    - master

clone_folder: /usr/go/src/github.com/timeforaninja/go-hms

environment:
  GOPATH: /usr/go/

stack: go 1.11

image:
  - Ubuntu1804

install:
  - echo $PATH
  - echo $GOPATH
  - go version
  - go env
  - sh: sudo apt install libssl-dev
  - go get -u github.com/xeodou/go-sqlcipher
  - go get -u golang.org/x/crypto/bcrypt

build_script:
  - go build -o bin/go-hms-{version}

artifacts:
  - path: bin/hms
    name: binary_linux
