version: "{branch}-v1.0.0-{build}"

branches:
  only:
    - master

clone_folder: /usr/local/go/src/github.com/timeforaninja/go-hms

image:
  - Ubuntu1804

stack: go 1.11

install:
  - sh: GOPATH=/usr/local/go
  - sh: echo $PATH
  - sh: echo $GOPATH
  - go version
  - go env
  # libssl on linux & openssl on win already preinstalled
  - go get -u github.com/xeodou/go-sqlcipher
  - go get -u golang.org/x/crypto/bcrypt
  - go vet ./...

build_script:
  - go build -o bin/go-hms

artifacts:
  - path: bin/go-hms
    name: binary_linux
