version: "{branch}-v1.0.0-{build}"

branches:
  only:
    - master

clone_folder: /usr/go/src/github.com/timeforaninja/go-hms

image:
  - Ubuntu1804

stack: go 1.11

environment:
  GOPATH: /usr/go/

before_test:
  - go vet /usr/go/src/github.com/timeforaninja/go-hms/

install:
  - sh: rm -rf /usr/go/src/github.com/timeforaninja/go-hms/.git
  - echo "build-info:"
  - echo $PATH
  - echo $GOPATH
  - echo $PWD
  - ls -lahR /usr/go/src/github.com/timeforaninja/go-hms
  # wait 3 seconds for the prev command
  - sh: sleep 3
  - go version
  - go env
  # libssl on linux & openssl on win already preinstalled
  - go get -u github.com/xeodou/go-sqlcipher
  - go get -u golang.org/x/crypto/bcrypt

build_script:
  - bash /usr/go/src/github.com/timeforaninja/go-hms/build.sh

artifacts:
  - path: /usr/go/src/github.com/timeforaninja/go-hms/artifacts
    name: hms-linux
  - path: /usr/go/src/github.com/timeforaninja/go-hms/artifacts
    name: hms-windows.exe
  - path: /usr/go/src/github.com/timeforaninja/go-hms/artifacts
    name: sql_schema.html
  - path: /usr/go/src/github.com/timeforaninja/go-hms/artifacts
    name: sql_schema.png
