version: "{branch}-v1.0.0-{build}"

branches:
  only:
    - master

clone_folder: ~/go/src/github.com/timeforaninja/go-hms

image:
  - Ubuntu1804

stack: go 1.11

install:
  - sh: GOPATH=~/go
  - sh: echo "build-info:"
  - sh: echo $PATH
  - sh: echo $GOPATH
  - sh: echo $PWD
  - go version
  - go env
  # libssl on linux & openssl on win already preinstalled
  - go get -u github.com/xeodou/go-sqlcipher
  - go get -u golang.org/x/crypto/bcrypt

test_script:
  - go vet $GOPATH/src/github.com/timeforaninja/go-hms

build_script:
  - sh: sudo $GOPATH/src/github.com/timeforaninja/go-hms/build.sh

artifacts:
  - path: artifacts
    name: hms-linux
  - path: artifacts
    name: hms-windows.exe
  - path: artifacts
    name: sql_schema.html
  - path: artifacts
    name: sql_schema.png
