version: "{branch}-v1.0.0-{build}"

branches:
  only:
    - master

image:
  - Ubuntu1804

clone_folder: /home/appveyor/projects/go/src/github.com/timeforaninja/go-hms

stack: go 1.11

install:
  - GOPATH=/home/appveyor/projects/go
  - rm -rf $GOPATH/src/github.com/timeforaninja/go-hms/.git
  - echo "build-info:"
  - echo $PATH
  - echo $GOPATH
  - echo $PWD
  - ls -lahR $GOPATH/src/github.com/timeforaninja/go-hms
  # wait 3 seconds for the prev command
  - sleep 3
  - go version
  - go env
  # libssl on linux & openssl on win already preinstalled
  - go get -u github.com/xeodou/go-sqlcipher
  - go get -u golang.org/x/crypto/bcrypt

build_script:
  - bash $GOPATH/src/github.com/timeforaninja/go-hms/build.sh

before_test:
  - go vet $GOPATH/src/github.com/timeforaninja/go-hms/
  # golangci-lint run $GOPATH/src/github.com/timeforaninja/go-hms/

artifacts:
  - path: artifacts
    name: hms-linux
  - path: artifacts
    name: hms-windows.exe
  - path: artifacts
    name: sql_schema.html
  - path: artifacts
    name: sql_schema.png
